// priority: 999

global.marterial = ["copper", "iron", "gold"];

global.blacklist = [
   "minecraft:wooden_sword",
   "minecraft:wooden_shovel",
   "minecraft:wooden_pickaxe",
   "minecraft:wooden_axe",
   "minecraft:wooden_hoe",
   "minecraft:stone_sword",
   "minecraft:stone_shovel",
   "minecraft:stone_pickaxe",
   "minecraft:stone_axe",
   "minecraft:stone_hoe",
   "minecraft:iron_sword",
   "minecraft:iron_shovel",
   "minecraft:iron_pickaxe",
   "minecraft:iron_axe",
   "minecraft:iron_hoe",
   "minecraft:golden_sword",
   "minecraft:golden_shovel",
   "minecraft:golden_pickaxe",
   "minecraft:golden_axe",
   "minecraft:golden_hoe",
   "minecraft:diamond_sword",
   "minecraft:diamond_shovel",
   "minecraft:diamond_pickaxe",
   "minecraft:diamond_axe",
   "minecraft:diamond_hoe",
   "minecraft:netherite_sword",
   "minecraft:netherite_shovel",
   "minecraft:netherite_pickaxe",
   "minecraft:netherite_axe",
   "minecraft:netherite_hoe",
   "immersiveengineering:sword_steel",
   "immersiveengineering:shovel_steel",
   "immersiveengineering:pickaxe_steel",
   "immersiveengineering:axe_steel",
   "immersiveengineering:hoe_steel",
   "ad_astra:iron_plate",
   "ad_astra:steel_plate",
   "tconstruct:steel_ingot",
   "mekanism:ingot_steel",
   "ad_astra:steel_ingot",
];

console.info("Loaded init");
